### ISSUE TITLE
Typo install-fan-service.sh

### ISSUE THREAD

**Issue by N15Telescope** [geekworm-com/x735-script#3]
line 7 of code has "sudp".
**sudp** cp -f ./pwm_fan_control.py         /usr/local/bin/

line 7 of code should be "sudo"
**sudo** cp -f ./pwm_fan_control.py         /usr/local/bin/

**Comment by geekworm-com** [comment]
Thanks. Updated

**Comment by geekworm-com** [comment]
Thanks. Updated.

Using `pwm_fan_control.py` is another way to make the PWM fan run. When we cannot edit the `/boot/config.txt` file (for example, in umbrel 1.0, the /boot directory is read-only), we cannot use a shell script to make the fan runs, you can use `python3 pwm_fan.control.py` to make the fan runs.

For reference:
https://wiki.geekworm.com/X735-script#How_to_make_the_fan_run_after_upgrading_umbrel_to_1.0

**Comment by N15Telescope** [comment]
Thanks for quick response.

Closed
